<?php

include_once 'optellen.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-08 at 16:26:52.
 */
class OptellenTest extends PHPUnit_Framework_TestCase {

    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        // nothing to set up
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
	
    public function testOptellen() {
        $this->assertEquals(0, optellen(0,0), "0+0");
		$this->assertEquals(0, optellen(-1,1));
		$this->assertEquals(0, optellen(1,-1));
		$this->assertEquals(0, optellen(-1000,1000));
		
		$this->assertEquals(-10, optellen(-5,-5));	// can return a negative value
		
		$this->assertEquals(20, optellen(10,10));
		$this->assertEquals(PHP_INT_MAX, optellen(PHP_INT_MAX,0));
		$this->assertEquals(PHP_INT_MAX + 1, optellen(PHP_INT_MAX,1));
		$this->assertEquals(PHP_INT_MAX + PHP_INT_MAX, optellen(PHP_INT_MAX,PHP_INT_MAX));
		$this->assertGreaterThan(PHP_INT_MAX, optellen(PHP_INT_MAX,PHP_INT_MAX));
		$this->assertGreaterThanOrEqual(2*PHP_INT_MAX, optellen(PHP_INT_MAX,PHP_INT_MAX));
    }
	public function data() {
		return array(
			array(0,0,0),
			array(-1,1,0),
			array(100,100, 200)
		);
	}
	
	/**
	* @dataProvider data
	*/
	function testMetData($a,$b,$c) {
		$this->assertEquals($c, optellen($a, $b), "$a + $b");
	}

}
